# Production Database
spring.datasource.url=jdbc:postgresql://${SUPABASE_HOST}:${SUPABASE_PORT}/${SUPABASE_DATABASE}?sslmode=verify-full&sslrootcert=/etc/ssl/certs/supabase/prod-ca-2021.crt
spring.datasource.hikari.ssl-mode=VERIFY_FULL
spring.datasource.hikari.ssl-root-cert=/etc/ssl/certs/supabase/prod-ca-2021.crt
spring.datasource.username=${SUPABASE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false

# Enable response compression
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/javascript,application/json

# JWT configuration
jwt.secret=${JWT_SECRET}

# Use the default port or specify a non-privileged port
server.port=8080

# Allow requests from the local machine only (if using a reverse proxy)
server.address=127.0.0.1
cors.allowed-origins=https://mendrx.in
# change to none after 1st run
spring.jpa.hibernate.ddl-auto=update



# Trust the X-Forwarded-* headers from Nginx
server.forward-headers-strategy=FRAMEWORK

tracker.folder.path=/opt/mendrx/data/tracker
parameters.folder.path=/opt/mendrx/data/parameters
lifestyle.rec.template.folder.path=/opt/mendrx/data/lifestyle-rec

spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=0
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=0